apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: github-influenceio
  name: github-influenceio
  namespace: default
spec:
  selector:
    matchLabels:
      app: github-influenceio
      version: v1
  template:
    metadata:
      labels:
        app: github-influenceio
        version: v1
    spec:
      containers:
      - image: gcr.io/influence-197607/github-influenceio:latest
        name: github-influenceio
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: mongo
        - name: REDIS_HOST
          value: "35.237.30.58"
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: environment
              key: sendgridkey
        - name: STRIPE_KEY
          valueFrom:
            secretKeyRef:
              name: environment
              key: stripekey
